Repository Richrook/Degree, pull requests merged in 2021-11, with the labels that each got.

#27 fix: ステージ選択画面とオプションの修正
  Assets/MyGame/Scenes/StageSelectScene.unity
Labels: bug

#33 31 create pause menu
  Assets/MyGame/Prefabs/OptionCanvas.prefab
  Assets/MyGame/Scripts/UIManager.cs
Labels: enhancement

#34 29 from title to stage select
  Assets/MyGame/Scenes/TitleScene.unity
  Assets/MyGame/Scripts/StageSelectButtonScript.cs
  Assets/MyGame/Scripts/StageSelectButtonScript.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#36 omnisharp 関連情報の削除し忘れを削除
  docs/README.md
  docs/setup_omnisharp.md
Labels: documentation
