Repository Richrook/Degree, pull requests merged in 2022-02, with the labels that each got.

#102 Issue 作成時タイトルに prefix を付けない
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/task.md
Labels: documentation

#100 StageControlScript.cs のリファクタリング
  Assets/MyGame/Scenes/SampleStageScene.unity
  Assets/MyGame/Scripts/StageControlScript.cs
  Assets/MyGame/Scripts/UIControlScript.cs
  Assets/MyGame/Scripts/UIControlScript.cs.meta
Labels: refactor

#98 ライフとPiのUI用の画像を追加
  Assets/MyGame/Material/LifeImage.png
  Assets/MyGame/Material/LifeImage.png.meta
  Assets/MyGame/Material/PiImage.png
  Assets/MyGame/Material/PiImage.png.meta
  Assets/MyGame/Scenes/SampleStageScene.unity
Labels: enhancement

#105 ライフとPiの色味を調節した
  Assets/MyGame/Scenes/SampleStageScene.unity
Labels: bug

#106 ライフとPiのUIを画面の大きさに合わせて調整
  Assets/MyGame/Scenes/SampleStageScene.unity
Labels: enhancement

#108 Piのオブジェクトをblenderで作り直した
  Assets/MyGame/Material/PiMainUnitMaterial.mat
  Assets/MyGame/Material/PiMainUnitMaterial.mat.meta
  Assets/MyGame/Material/white.mat
  Assets/MyGame/Material/white.mat.meta
  Assets/MyGame/Models/PiModel.fbx
  Assets/MyGame/Models/PiModel.fbx.meta
  Assets/MyGame/Prefabs/Pi.prefab
  Assets/MyGame/Scenes/SampleStageScene.unity
  Assets/MyGame/Scripts/PiControlScript.cs
Labels: bug

#115 111 revise retry bug
  Assets/MyGame/Scripts/PlayerStateMGTScript.cs
  Assets/MyGame/Scripts/StageControlScript.cs
  Assets/MyGame/Scripts/State.cs
Labels: bug
