Repository Richrook/Degree, pull requests merged in 2022-03, with the labels that each got.

#124 GameOver処理の書き換え
  Assets/MyGame/Scripts/PlayerStateMGTScript.cs
  Assets/MyGame/Scripts/StageControlScript.cs
Labels: refactor

#126 クリア画面のボタンが効かないバグの修正
  Assets/MyGame/Scenes/GameClearScene.unity
  Assets/MyGame/Scenes/SampleStageScene.unity
Labels: bug

#130 外部アセットの保存場所統一に伴い不要になった記述を削除
  .gitignore
  Assets/MyGame/Library/.gitkeep
Labels: documentation

#135 ステージのテンプレートを作成
  Assets/MyGame/Prefabs/Pi.prefab
  Assets/MyGame/Scenes/StageSceneTemplate.unity
  Assets/MyGame/Scenes/StageSceneTemplate.unity.meta
  ProjectSettings/SceneTemplateSettings.json
  docs/ステージ作成.md
Labels: enhancement

#141 敵から距離を取る処理を作成
  Assets/MyGame/Scripts/PlayerStateMGTScript.cs
Labels: enhancement

#137 ミニマップの作成
  Assets/MyGame/Images.meta
  Assets/MyGame/Images/EnemyIcon.png
  Assets/MyGame/Images/EnemyIcon.png.meta
  Assets/MyGame/Images/GoalIcon.png
  Assets/MyGame/Images/GoalIcon.png.meta
  Assets/MyGame/Images/LifeIcon.png
  Assets/MyGame/Images/LifeIcon.png.meta
  Assets/MyGame/Images/MinimapFrame.png
  Assets/MyGame/Images/MinimapFrame.png.meta
  Assets/MyGame/Images/MinimapMask.png
  Assets/MyGame/Images/MinimapMask.png.meta
  Assets/MyGame/Images/PiIcon.png
  Assets/MyGame/Images/PiIcon.png.meta
  Assets/MyGame/Images/PlayerIcon.png
  Assets/MyGame/Images/PlayerIcon.png.meta
  Assets/MyGame/Prefabs/Goal.prefab
  Assets/MyGame/Prefabs/Life.prefab
  Assets/MyGame/Prefabs/Pi.prefab
  Assets/MyGame/Scenes/SampleStageScene.unity
  Assets/MyGame/Scenes/StageSceneTemplate.unity
  Assets/MyGame/Scripts/UIControlScript.cs
  Assets/MyGame/Texture.meta
  Assets/MyGame/Texture/MinimapRender.renderTexture
  Assets/MyGame/Texture/MinimapRender.renderTexture.meta
  ProjectSettings/Packages/com.unity.probuilder/Settings.json
  ProjectSettings/SceneTemplateSettings.json
  ProjectSettings/TagManager.asset
  docs/ステージ作成.md
Labels: enhancement

#144 Update ステージ設定.md
  docs/ステージ設定.md
Labels: documentation

#149 敵を追加
  Assets/MyGame/Animators.meta
  Assets/MyGame/Animators/Beholder Animator Controller.controller
  Assets/MyGame/Animators/Beholder Animator Controller.controller.meta
  Assets/MyGame/Animators/Chest Monster Animator Controller.controller
  Assets/MyGame/Animators/Chest Monster Animator Controller.controller.meta
  Assets/MyGame/Animators/Slime Animator Controller.controller
  Assets/MyGame/Animators/Slime Animator Controller.controller.meta
  Assets/MyGame/Animators/Turtle Shell Animator Controller.controller
  Assets/MyGame/Animators/Turtle Shell Animator Controller.controller.meta
  Assets/MyGame/Scenes/StageSceneTemplate.unity
  Assets/MyGame/Scenes/StageSceneTemplate.unity.meta
  Assets/MyGame/Scripts/AttackScript.cs
  Assets/MyGame/Scripts/AttackScript.cs.meta
  Assets/MyGame/Scripts/EnemyControlScript.cs
  Assets/MyGame/Scripts/EnemyControlScript.cs.meta
  Assets/MyGame/Scripts/PlayerStateMGTScript.cs
  Assets/MyGame/Scripts/SearchPlayerScript.cs
  Assets/MyGame/Scripts/SearchPlayerScript.cs.meta
  Assets/MyGame/Scripts/SetPositionScript.cs
  Assets/MyGame/Scripts/SetPositionScript.cs.meta
  docs/ステージ設定.md
Labels: enhancement
